using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Count4U.Model
{
	public enum ImportProviderEnum
	{
		ImportLocationADOProvider = 0,
		ImportIturADOProvider = 1,
		ImportCatalogUnizagADOProvider = 2,
		ImportCatalogUnizagADOProvider1 = 3,
		ImportInventProductSimpleADOProvider = 4,
		ImportCatalogForComaxASPADOProvider = 5,
		ImportCatalogForComaxASPADOProvider1 = 6,
		ImportCatalogGazitVerifoneADOProvider = 7,
		ImportHamarotGazitVerifoneADOProvider2 = 8,
		ImportHamarotGazitVerifoneADOProvider1 = 9,
		ImportCatalogFromDBADOProvider = 10,
		ImportIturFromDBADOProvider = 11,
		ImportLocationFromDBADOProvider = 12,
		ImportCatalogFromDBBulkProvider = 13,
		ImportCatalogPriorityRenuarADOProvider = 14,
		ImportCatalogPriorityRenuarADOProvider1 = 15,
		ImportIturERPADOProvider = 16,
		//ExportCatalogToFileProvider = 11
		ImportCatalogNetPOSSuperPharmADOProvider = 17,
		ImportCatalogNetPOSSuperPharmADOProvider1 = 18,
		ImportSectionDefaultADOProvider = 19,
		ImportSectionFromDBADOProvider = 20,
		ImportCatalogNetPOSSuperPharmUpdateERPQuentetyADOProvider = 21,
		ImportBranchXtechMeuhedetProvider = 22,
		ImportBranchDefaultProvider = 23,
		ImportBranchGazitVerifoneProvider = 24,
		ImportCatalogXtechMeuhedetADOProvider1 = 25,
		ImportCatalogXtechMeuhedetADOProvider2 = 26,
		ImportCatalogXtechMeuhedetUpdateERPQuentetyADOProvider = 27,
		ImportCatalogYarpaADOProvider,
		ImportCatalogYarpaUpdateERPQuentetyADOProvider1,
		ImportCatalogYarpaUpdateERPQuentetyADOProvider2,
		ImportCatalogYarpaADOProvider1,
		ImportInventProductSimpleYarpaADOProvider,
		ImportInventProductAdvancedADOProvider,
		ImportInventProductAdvancedYarpaADOProvider,
		ImportCatalogYarpaWindowsADOProvider,
		ImportCatalogYarpaUpdateERPQuentetyWindowsADOProvider1,
		ImportCatalogYarpaUpdateERPQuentetyWindowsADOProvider2,
		ImportCatalogYarpaWindowsADOProvider1,
		ImportCatalogGeneralCSVUpdateERPQuentetyADOProvider1,
		ImportCatalogGeneralCSVADOProvider,
		ImportCatalogGeneralCSVADOProvider1,
		ImportSectionGeneralCSVADOProvider,
		ImportCatalogAvivPOSADOProvider,
		ImportCatalogAvivPOSADOProvider1,
		ImportCatalogAvivPOSUpdateERPQuentetyADOProvider1,
		ImportCatalogAvivMultiADOProvider,
		ImportCatalogAvivMultiADOProvider1,
		ImportCatalogAvivMultiUpdateERPQuentetyADOProvider1,
		ImportSupplierFromDBADOProvider,
		ImportSupplierAvivPOSADOProvider,
		ImportSupplierComaxASPADOProvider,
		ImportSupplierDefaultADOProvider,
		ImportCatalogMikramSonolADOProvider,
		ImportCatalogMikramSonolADOProvider1,
		ImportCatalogMikramSonolUpdateERPQuentetyADOProvider,
		ImportBranchMikramSonolProvider,
		ImportSectionMikramSonolADOProvider,
		ImportInventProductBulkProvider1,
		ImportCatalogPriorityKedsUpdateERPQuentetyADOProvider1,
		ImportCatalogPriorityKedsADOProvider1,
		ImportCatalogPriorityKedsADOProvider,
		ImportCatalogAvivPOSADOProvider2,
		ImportCatalogNetPOSSuperPharmBulkProvider,
		ImportCatalogRetalixPosHOUpdateERPQuentetyADOProvider,
		ImportCatalogRetalixPosHOADOProvider,
		ImportUnitPlanEFProvider,
		ImportUnitPlanDBEFProvider,
		ImportUnitPartDBEFProvider,
		ImportPartUnitEFProvider,
		ImportCatalogAS400LeumitADOProvider,
		ImportCatalogAS400LeumitADOProvider1,
		ImportCatalogAS400LeumitUpdateERPQuentetyADOProvider1,
		ImportBranchAS400LeumitProvider,
		ImportCatalogMiniSoftADOProvider,
		ImportCatalogMiniSoftADOProvider1,
		ImportCatalogRetalixNextADOProvider,
		ImportCatalogRetalixNextADOProvider1,
		ImportCatalogRetalixNextBulkProvider,
		ImportCatalogRetalixNextUpdateERPQuentetyADOProvider,
		ImportCatalogOne1ADOProvider,
		ImportCatalogOne1ADOProvider1,
		ImportCatalogOne1UpdateERPQuentetyADOProvider,
		ImportCatalogAS400AmericanEagleADOProvider,
		ImportCatalogAS400AmericanEagleADOProvider1,
		ImportCatalogMaccabiPharmSAPADOProvider,
		ImportCatalogMaccabiPharmSAPADOProvider1,
		ImportCatalogMaccabiPharmSAPUpdateERPQuentetyADOProvider1,
		ImportCatalogMaccabiPharmSAPADOProvider2,
		ImportEmulationLocationADOProvider,
		ImportFamilyPriorityRenuarADOProvider,
		ImportCatalogComaxASPMultiBarcodeADOProvider2,
		ImportCatalogComaxASPMultiBarcodeADOProvider1,
		ImportCatalogComaxASPMultiBarcodeADOProvider,
		ImportCatalogMikiKupotProvider,
		ImportFamilyLadyComfortADOProvider,
		ImportCatalogLadyComfortADOProvider,
		ImportCatalogMade4NetADOProvider,
		ImportFamilyMade4NetADOProvider,
		ImportSupplierMade4NetADOProvider,
		ImportCatalogMade4NetADOProvider1,
		ImportCatalogAS400JaforaProvider,
		ImportSupplierNibitADOProvider,
		ImportCatalogNibitADOProvider,
		ImportCatalogNibitADOProvider1,
		ImportCatalogNibitUpdateERPQuentetyADOProvider,
		ImportCatalogOrenOriginalsProvider,
		ImportCatalogOrenOriginalsProvider1,
		ImportCatalogNimrodAvivProvider,
		ImportCatalogNimrodAvivProvider1,
		ImportCatalogNimrodAvivProvider2,
		ImportSectionNimrodAvivProvider,
		ImportCatalogH_MProvider,
		ImportCatalogH_MProvider1,
		ImportFamilyH_MProvider,
		ImportSectionH_MProvider,
		ImportCatalogH_MProvider2,
		ImportCatalogH_MProvider3,
		ImportCatalogAS400AprilProvider,
		ImportCatalogAS400AprilProvider1,
		ImportCatalogAS400AprilUpdateERPQuentetyProvider,
		ImportSupplierAS400AprilProvider,
		ImportCatalogBazanCsvProvider,
		ImportCatalogPriorityKedsShowRoomProvider,
		ImportFamilyPriorityKedsShowRoomProvider,
		ImportCatalogHashProvider1,
		ImportCatalogHashProvider,
		ImportCatalogNibitADOProvider0,
		ImportCatalogAS400MangoProvider,
		ImportCatalogAS400MangoProvider1,
		ImportIturFacingProvider,
		ImportShelfFacingProvider,
		ImportSectionFRSVisionMirkamProvider,
		ImportSupplierFRSVisionMirkamADOProvider,
		ImportCatalogFRSVisionMirkamADOProvider,
		ImportCatalogFRSVisionMirkamADOProvider1,
		ImportCatalogUnizagADOProvider2,
		ImportCatalogUnizagADOProvider3,
		ImportCatalogAS400HonigmanProvider2,
		ImportCatalogAS400HonigmanProvider1,
		ImportCatalogAS400HonigmanProvider,
		ImportBranchAS400HonigmanProvider,
		ImportCatalogIturQuantityProvider,
		ImportCatalogMPLUpdateERPQuentetyProvider1,
		ImportCatalogMPLProvider2,
		ImportCatalogMPLProvider1,
		ImportCatalogMPLProvider,
		ImportSectionMPLProvider,
		ImportInventProductADOProvider1,
		ImportCatalogAS400AmericanEagleADOProvider2,
		ImportCatalogAS400AmericanEagleADOProvider3,
		ImportInventProductMisADOProvider,
		ImportCatalogTafnitMatrixProvider1,
		ImportCatalogTafnitMatrixProvider,
		ImportSectionTafnitMatrixProvider,
		ImportCatalogTafnitMatrixUpdateERPQuentetyProvider,
		ImportCatalogTafnitMatrixProvider2,
		ImportCatalogPriorityCastroProvider,
		ImportCatalogPriorityCastroProvider1,
		ImportBranchPriorityCastroProvider,
		ImportCatalogGeneralXLSXProvider1,
		ImportCatalogGeneralXLSXProvider,
		ImportCatalogGeneralXLSXUpdateERPQuentetyADOProvider1,
		ImportSectionGeneralXLSXProvider,
		ImportSupplierGeneralXLSXProvider,
		ImportCatalogOrenOriginalsProvider2,
		ImportCatalogOrenOriginalsUpdateERPQuentetyProvider1,
		ImportFamilyTafnitMatrixProvider,
		ImportCatalogOtechProvider,
		ImportCatalogOtechProvider1,
		ImportCatalogOtechUpdateERPQuentetyADOProvider,
		ImportCatalogOtechProvider2,
		ImportFamilyDefaultProvider,
		ImportCatalogNikeIntProvider,
		ImportCatalogNikeIntProvider1,
		ImportCatalogNikeIntProvider2,
		ImportCatalogNikeIntUpdateERPQuentetyProvider,
		ImportInventProductWarehouseADOProvider,
		ImportCatalogWarehouseXslxProvider,
		ImportCatalogWarehouseXslxProvider1,
		ImportCatalogWarehouseXslxProvider2,
		ImportCatalogWarehouseXslxProvider3,
		ImportLocationXlsxProvider,
		ImportLocationUpdateTagProvider,
		ImportInventProductDB3Provider,
		ImportCatalogSapb1XslxProvider,
		ImportCatalogSapb1XslxProvider1,
		ImportCatalogSapb1XslxUpdateERPQuentetyProvider1,
		ImportCatalogMerkavaSqliteXslxUpdateERPQuentetyProvider1,
		ImportCatalogMerkavaSqliteXslxProvider,
		ImportCatalogMerkavaSqliteXslxProvider1,
		ImportLocationMerkavaXslx2SqliteProvider,
		ImportIturMerkavaSqliteXslxProvider,
		ImportPropertyStr6MerkavaXslx2SdfProvider,
		ImportPropertyStr7MerkavaXslx2SdfProvider,
		ImportPropertyStr7MerkavaXslx2SdfProvider1,
		ImportBranchDefautXlsxProvider,
		ImportCatalogMerkavaXslxProvider,
		ImportCatalogMerkavaXslxProvider1,
		ImportCatalogMerkavaXslxUpdateERPQuentetyProvider1,
		ImportLocationMerkavaXslx2SdfProvider,
		ImportIturMerkavaXslx2SdfProvider,
		//ImportBuildingConfigSQLiteADORepository,
		//ImportCatalogSQLiteADORepository,
		ImportBuildingConfigMerkavaSqliteXslxProvider,
		ImportPropertyStr6ListMerkavaSqliteXslxProvider,
		ImportPropertyStr7ListMerkavaSqliteXslxProvider,
		ImportPreviousInventoryMerkavaSqliteXslxProvider,
		ImportCatalogSapb1ZometsfarimProvider,
		ImportCatalogSapb1ZometsfarimProvider1,
		ImportCatalogSapb1ZometsfarimProvider2,
		ImportCatalogSapb1ZometsfarimProvider3,
		ImportCatalogSapb1ZometsfarimUpdateERPQuentetyProvider,
		ImportSupplierSapb1ZometsfarimProvider,
		ImportSectionSapb1ZometsfarimProvider,
		ImportSectionSapb1ZometsfarimProvider1,
		ImportInventProductMisAndDefaultADOProvider,
		ImportCatalogGazitVerifoneSteimaztzkyProvider,
		ImportCatalogGazitVerifoneSteimaztzkyProvider1,
		ImportCatalogGazitVerifoneSteimaztzkyUpdateERPQuentetyProvider,
		UpdateCatalogERPQuantityGazitVerifoneSteimaztzkyAdapter,
		ImportSectionGazitVerifoneSteimaztzkyProvider1,
		ImportSectionGazitVerifoneSteimaztzkyProvider,
		ImportPreviousInventoryMerkavaDbSetProvider,
		ImportBuildingConfigMerkavaXslx2SdfProvider,
		ImportBuildingConfigMerkavaSdf2SqliteProvider,
		ImportCatalogMerkavaSdf2SqliteProvider,
		ImportLocationMerkavaSdf2SqliteProvider,
		ImportPreviousInventoryMerkavaSdf2SqliteProvider,
		ImportPropertyStr7ListMerkavaSdf2SqliteProvider,
		ImportPropertyStr6ListMerkavaSdf2SqliteProvider,
		ImportInventProductMerkavaSqlite2SdfProvider,
		ImportCurrentInventorMerkavaSdf2SqliteProvider,
		ImportLocationUpdateMerkavaSqlite2SdfProvider,
		ImportCatalogClalitSdf2SqliteProvider,
		ImportLocationClalitSdf2SqliteProvider,
		ImportBuildingConfigClalitSdf2SqliteProvider,
		ImportPreviousInventoryClalitSdf2SqliteProvider,
		ImportCurrentInventorClalitSdf2SqliteProvider,
		ImportLocationUpdateClalitSqlite2SdfProvider,
		ImportInventProductClalitSqlite2SdfProvider,
		ImportCatalogClalitXslxProvider,
		ImportLocationClalitXslx2SdfProvider,
		ImportIturClalitXslx2SdfProvider,
		ImportBuildingConfigClalitXslx2SdfProvider,
		ImportPropertyStrClalitXslx2SdfProvider1,
		ImportPropertyStrClalitXslx2SdfProvider2,
		ImportPropertyStrClalitXslx2SdfProvider3,
		ImportPropertyStrClalitXslx2SdfProvider4,
		ImportPropertyStrClalitXslx2SdfProvider5,
		ImportPreviousInventoryClalitDbSetProvider,
		ImportPropertyStrListClalitSdf2SqliteProvider1,
		ImportPropertyStrListClalitSdf2SqliteProvider2,
		ImportPropertyStrListClalitSdf2SqliteProvider4,
		ImportPropertyStrListClalitSdf2SqliteProvider5,
		ImportPropertyStrListClalitSdf2SqliteProvider3,
		ImportTemporaryInventoryMerkavaSqlite2SdfProvider,
		ImportSectionAS400MegaProvider,
		ImportCatalogAS400MegaProvider,
		ImportCatalogAS400MegaProvider1,
		ImportCatalogAS400MegaUpdateERPQuentetyProvider,
		ImportSupplierAS400MegaProvider,
		ImportTemporaryInventoryClalitSqlite2SdfProvider,
		ImportCatalogNativXslx2SdfProvider,
		ImportCatalogNativXslxProvider1,
		ImportLocationNativXslx2SdfProvider,
		ImportIturNativXslx2SdfProvider,
		ImportBuildingConfigNativXslx2SdfProvider,
		ImportPreviousInventoryNativDbSetProvider,
		ImportCatalogNativSdf2SqliteProvider,
		ImportLocationNativSdf2SqliteProvider,
		ImportBuildingConfigNativSdf2SqliteProvider,
		ImportPreviousInventoryNativSdf2SqliteProvider,
		ImportCurrentInventorNativSdf2SqliteProvider,
		ImportTemporaryInventoryNativSqlite2SdfProvider,
		ImportLocationUpdateNativSqlite2SdfProvider,
		ImportInventProductNativSqlite2SdfProvider,
		ImportCatalogPriorityAldoProvider1,
		ImportCatalogPriorityAldoProvider,
		ImportInventProductDefaultBackupProvider,
		ImportPropertyStr1NativXslx2SdfProvider,
		ImportPropertyStr2NativXslx2SdfProvider,
		ImportPropertyStr3NativXslx2SdfProvider,
		ImportCatalogNativXslxUpdateERPQuentetyProvider1,
		ImportCatalogNativSqlite2SdfProvider,
		ImportInventProductFromDbBulkProvider,
		ImportIturFromDBProvider,
		ImportIturFromDBBlukProvider,
		ImportDocumentHeaderFromDBBlukProvider,
		ForwardInventProductMalamFileProvider,
		ForwardInventProductMalamDataSetProvider,
		ImportCatalogPrioritySweetGirlXLSXProvider,
		ImportInventProductBulkUpdateProvider,
		ImportPropertyStr18MerkavaXslx2SdfProvider,
		ImportPropertyStr18ListMerkavaSdf2SqliteProvider,
		ImportPropertyStr9NativXslx2SdfProvider,
		ImportPropertyStr7NativXslx2SdfProvider,
		ImportPropertyStr6NativXslx2SdfProvider,
		ImportPropertyStr5NativXslx2SdfProvider,
		ImportPropertyStr4NativXslx2SdfProvider,
		ImportPreviousInventoryNativPlusDbSetProvider,
		ImportPropertyStr1ListNativSdf2SqliteProvider,
		ImportPropertyStr2ListNativSdf2SqliteProvider,
		ImportPropertyStr3ListNativSdf2SqliteProvider,
		ImportPropertyStr4ListNativSdf2SqliteProvider,
		ImportPropertyStr5ListNativSdf2SqliteProvider,
		ImportPropertyStr6ListNativSdf2SqliteProvider,
		ImportPropertyStr7ListNativSdf2SqliteProvider,
		ImportPropertyStr8ListNativSdf2SqliteProvider,
		ImportPropertyStr9ListNativSdf2SqliteProvider,
		ImportPropertyStrUpdateNativSqlite2SdfProvider,
		ImportPropertyStr8NativXslx2SdfProvider,
		ImportPropertyStr10NativXslx2SdfProvider,
		ImportPropertyStr10ListNativSdf2SqliteProvider,
		ImportInventProductBulkUpdateProvider2,
		ImportInventProductBulkUpdateProvider3,
		ImportInventProductMinusByMakatFromDbBulkProvider,
		ImportInventProductUpdate2SumByIturMakatDbBulkProvider,
		ImportCatalogAS400HamashbirProvider,
		ImportCatalogAS400HamashbirProvider1,
		ImportCatalogAS400HamashbirProvider2,
		ImportSectionAS400HamashbirProvider,
		ImportCatalogAS400HamashbirUpdateERPQuentetyProvider,
		ImportInventProductUpdate2SumByIturDocMakatDbBulkProvider,
		ImportCatalogAS400HamashbirUpdateERPQuentetyProvider2,
		ImportTemplateInventoryNativXslx2SdfProvider,
		ImportTemplateInventoryNativPlusDbSetProvider,
		ImportTemplateInventoryNativSdf2SqliteProvider,
		ImportLocationUpdateNativSimpleSqlite2SdfProvider,
		ImportPropertyDecoratorNativXslx2SdfProvider,
		ImportInventProductNativPlusSqlite2SdfProvider,
		ImportLocationUpdateNativXslx2SdfProvider,
		ImportIturUpdateNativXslx2SdfProvider,
		ImportStatusInventProductNativPlusSqlite2SdfProvider,
		ImportStatusInventProductUpdateSumNativPlusSqlite2SdfProvider,
		ImportInventProductUpdateCompare2SumByIturMakatDbBulkProvider1,
		ImportInventProductUpdateCompare2SumByIturMakatDbBulkProvider2,
		ImportInventProductUpdateBarcodeFromDbBulkProvider,
		ImportFamilyAS400HamashbirProvider,
		ImportCatalogAS400HamashbirUpdateERPQuentetyProvider1,
		ImportInventProductUpdate2MakatAndSNDbBulkProvider,
		ImportInventProductUpdateMakat2BarcodeDbBulkProvider,
		ImportInventProductUpdate2SumByIturMakatSNumberDbBulkProvider,
		ImportCatalogGazitAlufHaSportXlsxProvider,
		ImportCatalogAS400HoProvider,
		ImportCatalogAS400HoProvider1,
		ImportCatalogAS400HoProvider2_2,
		ImportCatalogAS400HoProvider2_1,
		ImportInventProductUpdate2SumByIturBarcodeSNumberDbBulkProvider,
		ImportInventProductUpdate2BarcodeAndSNDbBulkProvider,
		ImportInventProductUpdate2SumByIturBarcodeDbBulkProvider,
		ImportDocumentHeaderAddFristDocToIturBlukProvider,
		ImportCatalogYesXlsxProviderSN,
		ImportCatalogYesXlsxProvider,
		ImportCatalogYesXlsxProviderQ,
		ImportLocationYesXlsxProviderQ,
		ImportLocationYesXlsxProviderSN,
		ImportIturYesXlsxProviderSN,
		ImportIturYesXlsxProviderQ,
		ImportInventProductYesXlsxProviderQ,
		ImportInventProductYesXlsxProviderSN,
		ImportPreviousInventoryNativYesDbSetProviderSN,
		ImportPreviousInventoryNativYesDbSetProviderQ,
		ImportFamilyGeneralXLSXProvider,
		ImportProfileNativXslx2SdfProvider,
		ImportCurrentInventorNativPlusSdf2SqliteProvider,
		ImportInventProductNativPlusMISSqlite2SdfProvider,
		ImportTemporaryInventoryNativPlusMISSqlite2SdfProvider,
		ImportCatalogNativMISSqlite2SdfProvider,
		ImportCatalogNativPlusMISSdf2SqliteProvider,
		ImportLocationNativPlusMISSdf2SqliteProvider,
		ImportBuildingConfigNativPlusMISSdf2SqliteProvider,
		ImportInventProductAfterCompareFromDbBulkProvider,
		ImportProfileXml2SdfProvider,
		ImportBranchXtechMeuhedetXlsxProvider,
		ImportCatalogXtechMeuhedetXLSXProvider,
		ImportCatalogXtechMeuhedetXLSXProvider1,
		ImportCatalogXtechMeuhedetXLSXUpdateERPQuentetyADOProvider1,
		ImportCatalogXtechMeuhedetXLSXProvider2,
		ImportInventProductBulkUpdateProvider4,
		ImportCatalogH_M_NewProvider,
		ImportCatalogH_M_NewProvider1,
		ImportCatalogH_M_NewProvider2,
		ImportCatalogH_M_NewProvider3,
		ImportSectionH_M_NewProvider,
		ImportFamilyH_M_NewProvider,
		ImportInventProductMerkavaXlsxProviderQ,
		ImportInventProductMerkavaXlsxProviderSN,
		ImportCatalogPrioritytEsteeLouderXslxProvider,
		ImportCatalogShalevetCsvProvider,
		ImportFamilyNativXslx2SdfProvider,
		ImportSectionNativXslx2SdfProvider,
		ImportSectionNativXslx2SdfProvider1,
		ImportSupplierNativXslx2SdfProvider,
		ImportCatalogGeneralXLSXUpdateERPQuentetyADOProvider2,
		ImportCatalogGazitLeeCooperProvider1,
		ImportCatalogGazitLeeCooperProvider,
		ImportLocationNativPlusLadpcProvider,
		ImportIturNativPlusLadpcProvider1,
		ImportCatalogNativPlusLadpcProvider,
		ImportPreviousInventoryNativPlusLadpcDbSetProvider,
		ImportIturNativPlusLadpcProvider9999,
		ImportCatalogGazitGlobalXlsxProvider,
		ImportCatalogPrioritytEsteeLouderUpdateERPQuentetyProvider,
		ImportSectionGazitGlobalXlsxProvider

	}

	public enum ExportProviderEnum
	{
		//ExportCatalogToFileProvider = 0,
		ExportIturToFileProvider = 1,
		ExportUserIniToFileProvider = 2,
		ExportCustomerConfigToFileProvider = 3,
		ExportInventProductComaxERPFileProvider = 4,
		ExportInventProductUnizagERPFileProvider = 5,
		ExportInventProductGazitERPFileProvider = 6,
		ExportInventProductPriorityRenuarERPFileProvider = 7,
		ExportInventProductPriorityRenuarERPFileProvider1 = 8,
		ExportInventProductNetPOSSuperPharmERPFileProvider = 9,
		ExportInventProductNetPOSSuperPharmERPFileProvider1 = 10,
		ExportInventProductXtechMeuhedetERPFileProvider = 11,
		ExportInventProductXtechMeuhedetERPFileProvider1 = 12,
		ExportCatalogPdaHt630FileProvider = 13,
		ExportIturPdaHt630FileProvider = 14,
		ExportInventProductYarpaERPFileProvider,
		ExportInventProductYarpaERPFileProvider1,
		ExportInventProductGeneralCSVERPFileProvider,
		ExportInventProductGeneralCSVERPFileProvider1,
		ExportInventProductAvivPOSERPFileProvider,
		ExportInventProductAvivMultiERPFileProvider,
		ExportInventProductAvivMultiERPFileProvider1,
		ExportInventProductMikramSonolERPFileProvider1,
		ExportInventProductMikramSonolERPFileProvider,
		ExportInventProductMikramTenERPFileProvider1,
		ExportInventProductMikramTenERPFileProvider,
		ExportInventProductPriorityKedsMatrixERPFileProvider,
		ExportInventProductPriorityKedsRegularERPFileProvider,
		ExportInventProductPriorityKedsERPFileProvider1,
		ExportInventProductMikramSonolSAPERPFileProvider1,
		ExportInventProductMikramSonolSAPERPFileProvider,
		ExportInventProductRetalixPosHOERPFileProvider,
		ExportInventProductRetalixPosHOERPFileProvider0,
		ExportInventProductRetalixPosHOERPFileProvider1,
		ExportInventProductAS400LeumitERPFileProvider1,
		ExportInventProductAS400LeumitERPFileProvider,
		ExportInventProductMiniSoftERPFileProvider,
		ExportInventProductMiniSoftERPFileProvider1,
		ExportInventProductGeneralCSVERPFileProvider2,
		ExportInventProductRetalixNextERPFileProvider1,
		ExportInventProductRetalixNextERPFileProvider0,
		ExportInventProductRetalixNextERPFileProvider,
		//ExportCatalogPdaHt630UploadProvider,
		ExportInventProductOne1ERPFileProvider,
		ExportInventProductMiniSoftERPFileProvider2,
		ExportInventProductAS400AmericanEagleERPFileProvider,
		ExportInventProductAS400AmericanEagleERPFileProvider1,
		ExportInventProductMaccabiPharmSAPERPFileProvider,
		ExportInventProductMaccabiPharmSAPERPFileProvider1,
		ExportInventProductPriorityRenuarERPFileProvider2,
		ExportInventProductMikiKupotERPFileProvider,
		ExportInventProductLadyComfortERPFileProvider,
		ExportInventProductLadyComfortERPFileProvider1,
		ExportInventProductMade4NetERPFileProvider,
		ExportInventProductMade4NetERPFileProvider1,
		ExportCatalogPdaMade4NetFileProvider,
		ExportInventProductAS400JaforaERPFileProvider2,
		ExportInventProductAS400JaforaERPFileProvider1,
		ExportInventProductAS400JaforaERPFileProvider,
		ExportInventProductNibitERPFileProvider,
		ExportInventProductNibitERPFileProvider1,
		ExportInventProductPriorityRenuarERPFileProvider_W,
		ExportInventProductPriorityRenuarERPFileProvider_T,
		ExportInventProductPriorityRenuarERPFileProvider_M,
		ExportInventProductOrenOriginalsERPFileProvider,
		ExportInventProductOrenOriginalsERPFileProvider1,
		ExportInventProductOrenOriginalsERPFileProvider2,
		ExportInventProductNimrodAvivERPFileProvider,
		ExportInventProductNimrodAvivERPFileProvider1,
		ExportInventProductNimrodAvivERPFileProvider2,
		ExportInventProductH_MERPFileProvider,
		ExportInventProductAS400AprilERPFileProvider,
		ExportInventProductAS400AprilERPFileProvider1,
		ExportInventProductBazanCsvERPFileProvider1,
		ExportInventProductPriorityKedsShowRoomERPFileProvider1,
		ExportInventProductPriorityKedsShowRoomERPFileProvider,
		ExportInventProductHashERPFileProvider1,
		ExportInventProductHashERPFileProvider,
		ExportInventProductAS400MangoERPFileProvider1,
		ExportInventProductAS400MangoERPFileProvider,
		ExportInventProductFRSVisionMirkamERPFileProvider1,
		ExportInventProductFRSVisionMirkamERPFileProvider,
		ExportInventProductAS400HonigmanERPFileProvider,
		ExportInventProductAS400HonigmanERPFileProvider1,
		ExportInventProductMPLFileProvider1,
		ExportInventProductMPLFileProvider,
		ExportCatalogPdaMISFileProvider,
		ExportIturPdaMISFileProvider,
		ExportCustomerMISConfigToFileProvider,
		ExportInventProductTafnitMatrixERPFileProvider,
		ExportInventProductTafnitMatrixERPFileProvider1,
		ExportInventProductPriorityCastroERPFileProvider,
		ExportInventProductPriorityCastroERPFileProvider1,
		ExportInventProductOtechERPFileProvider,
		ExportInventProductOtechERPFileProvider_M,
		ExportInventProductOtechERPFileProvider_T,
		ExportInventProductOtechERPFileProvider_W,
		ExportInventProductOtechERPFileProvider1,
		ExportInventProductOtechERPFileProvider2,
		ExportInventProductNikeIntERPFileProvider,
		ExportInventProductNikeIntERPFileProvider1,
		ExportInventProductWarehouseXslxFileProvider,
		ExportInventProductWarehouseXslxFileProvider1,
		ExportInventProductWarehouseXslxFileFormulaProvider,
		ExportInventProductSapb1XslxERPFileProvider1,
		ExportInventProductSapb1XslxERPFileProvider,
		ExportInventProductSapb1ZometsfarimERPFileProvider,
		ExportInventProductSapb1ZometsfarimERPFileProvider1,
		ExportInventProductGazitVerifoneSteimaztzkyERPFileProvider,
		ExportInventProductGazitVerifoneSteimaztzkyERPFileProvider1,
		ExportProductGazitVerifoneSteimaztzkyERPFileProvider,
		ExportInventProductClalitXlsxTemplateProvider1,
		ExportInventProductMerkavaTemplateProvider,
		ExportInventProductMerkavaTemplateProvider1,
		ExportInventProductMerkavaTemplateProvider2,
		ExportInventProductMerkavaProvider2_2,
		ExportInventProductMerkavaProvider2_1,
		ExportInventProductMerkavaGovProvider2_1,
		ExportInventProductMerkavaProvider1,
		ExportInventProductAS400MegaERPFileProvider,
		ExportInventProductAS400MegaERPFileProvider1,
		ExportInventProductNativProvider1,
		ExportInventProductYellowPazERPFileProvider,
		ExportInventProductPriorityAldoERPFileProvider,
		ExportInventProductAS400HonigmanERPFileProvider2,
		ExportInventProductUnizagERPFileProvider1,
		ExportInventProductPrioritySweetGirlXlsxErpFileProvider1,
		ExportInventProductPrioritySweetGirlXlsxErpFileProvider,
		ExportInventProductNativPlusProvider1,
		ExportInventProductMerkavaProvider3,
		ExportInventProductMerkavaProvider4,
		ExportInventProductMerkavaProvider5,
		ExportInventProductGeneralXslxFileProvider,
		ExportInventProductAS400HamashbirERPFileProvider1,
		ExportInventProductAS400HamashbirERPFileProvider,
		ExportInventProductNativPlusProvider2,
		ExportInventProductAS400HoProvider2,
		ExportInventProductAS400HoProvider1,
		ExportInventProductAS400HoProvider,
		ExportInventProductXtechMeuhedetXlsxProvider1,
		ExportInventProductXtechMeuhedetXlsxProvider,
		ExportInventProductXtechMeuhedetXlsxProvider2,
		ExportInventProductH_M_NewERPFileProvider,
		ExportInventProductNativPlusProvider1_Q,
		ExportInventProductNativPlusProvider1_SN,
		ExportInventProductNativPlusYesProvider2,
		ExportInventProductNativPlusYesProvider1_SN,
		ExportInventProductNativPlusYesProvider1,
		ExportInventProductNativPlusYesProvider1_Q,
		ExportInventProductNativPlusLadpcXslxProvider2,
		ExportInventProductNativPlusLadpcCsvProvider1,
		ExportInventProductGazitLeeCooperERPFileProvider,
		ExportInventProductNimrodAvivERPFileProvider3,
		ExportInventProductNativPlusMateAsherProvider1,
		ExportInventProductNativPlusMisradApnim,
		ExportInventProductStockSonigoXslxProvider1
	}

	public enum ExportRepositoryEnum
	{
		ExportCatalogSimpleFileRepository = 0,
		ExportIturFileRepository = 1,
		ExportInventProductSimpleERPFileRepository = 2,
		ExportUserIniFileRepository = 3,
		ExportCustomerConfigFileRepository = 4,
		ImportLocationADORepository = 5,
		ImportIturADORepository = 6,
		ImportCatalogSimpleADORepository = 7,
		ImportCatalogSqlBulkRepository = 8,
		ImportInventProductSimpleADORepository = 9,
		//UploadCatalogFileRepository
		ExportCustomerMISConfigFileRepository,
		ExportCurrentInventorAdvancedERPRepository,
	}


	public enum WriterEnum
	{
		//ExportCatalogFileWriter = 0,
		ExportIturFileWriter = 1,
		ExportUserIniFileWriter = 2,
		ExportCustomerConfigFileWriter = 3,
		ExportInventProductComaxERPFileWriter = 4,
		ExportInventProductUnizagERPFileWriter = 5,
		ExportInventProductGazitERPFileWriter = 6,
		ExportInventProductPriorityRenuarERPFileWriter = 7,
		ExportInventProductPriorityRenuarERPFileWriter1 = 8,
		ExportInventProductNetPOSSuperPharmERPFileWriter = 9,
		ExportInventProductNetPOSSuperPharmERPFileWriter1 = 10,
		ExportInventProductXtechMeuhedetERPFileWriter = 11,
		ExportInventProductXtechMeuhedetERPFileWriter1 = 12,
		ExportCatalogPdaHt630FileWriter = 13,
		ExportIturPdaHt630FileWriter = 14,
		ExportInventProductYarpaERPFileWriter1,
		ExportInventProductYarpaERPFileWriter,
		ExportInventProductGeneralCSVERPFileWriter,
		ExportInventProductGeneralCSVERPFileWriter1,
		ExportInventProductAvivPOSERPFileWriter,
		ExportInventProductAvivMultiERPFileWriter,
		ExportInventProductAvivMultiERPFileWriter1,
		ExportInventProductMikramSonolERPFileWriter,
		ExportInventProductMikramSonolERPFileWriter1,
		ExportInventProductMikramTenERPFileWriter,
		ExportInventProductMikramTenERPFileWriter1,
		ExportInventProductPriorityKedsMatrixERPFileWriter,
		ExportInventProductPriorityKedsRegularERPFileWriter,
		ExportInventProductPriorityKedsERPFileWriter1,
		ExportInventProductMikramSonolSAPERPFileWriter,
		ExportInventProductMikramSonolSAPERPFileWriter1,
		ExportInventProductRetalixPosHOERPFileWriter,
		ExportInventProductRetalixPosHOERPFileWriter1,
		ExportInventProductRetalixPosHOERPFileWriter0,
		ExportInventProductAS400LeumitERPFileWriter,
		ExportInventProductAS400LeumitERPFileWriter1,
		ExportInventProductMiniSoftERPFileWriter1,
		ExportInventProductMiniSoftERPFileWriter,
		ExportInventProductGeneralCSVERPFileWriter2,
		ExportInventProductRetalixNextERPFileWriter,
		ExportInventProductRetalixNextERPFileWriter0,
		ExportInventProductRetalixNextERPFileWriter1,
		ExportInventProductOne1ERPFileWriter,
		ExportInventProductMiniSoftERPFileWriter2,
		ExportInventProductAS400AmericanEagleERPFileWriter,
		ExportInventProductAS400AmericanEagleERPFileWriter1,
		ExportInventProductMaccabiPharmSAPERPFileWriter,
		ExportInventProductMaccabiPharmSAPERPFileWriter1,
		ExportInventProductPriorityRenuarERPFileWriter2,
		ExportInventProductMikiKupotERPFileWriter,
		ExportInventProductLadyComfortERPFileWriter,
		ExportInventProductLadyComfortERPFileWriter1,
		ExportInventProductMade4NetERPFileWriter,
		ExportInventProductMade4NetERPFileWriter1,
		ExportCatalogPdaMade4NetFileWriter,
		ExportInventProductAS400JaforaERPFileWriter,
		ExportInventProductAS400JaforaERPFileWriter2,
		ExportInventProductAS400JaforaERPFileWriter1,
		ExportInventProductNibitERPFileWriter,
		ExportInventProductNibitERPFileWriter1,
		ExportInventProductPriorityRenuarERPFileWriter_M,
		ExportInventProductPriorityRenuarERPFileWriter_T,
		ExportInventProductPriorityRenuarERPFileWriter_W,
		ExportInventProductOrenOriginalsERPFileWriter,
		ExportInventProductOrenOriginalsERPFileWriter1,
		ExportInventProductOrenOriginalsERPFileWriter2,
		ExportInventProductNimrodAvivERPFileWriter,
		ExportInventProductNimrodAvivERPFileWriter1,
		ExportInventProductNimrodAvivERPFileWriter2,
		ExportInventProductH_MERPFileWriter,
		ExportInventProductAS400AprilERPFileWriter1,
		ExportInventProductAS400AprilERPFileWriter,
		ExportInventProductBazanCsvERPFileWriter1,
		ExportInventProductPriorityKedsShowRoomERPFileWriter,
		ExportInventProductPriorityKedsShowRoomERPFileWriter1,
		ExportInventProductHashERPFileWriter,
		ExportInventProductHashERPFileWriter1,
		ExportInventProductAS400MangoERPFileWriter,
		ExportInventProductAS400MangoERPFileWriter1,
		ExportInventProductFRSVisionMirkamERPFileWriter1,
		ExportInventProductFRSVisionMirkamERPFileWriter,
		ExportInventProductAS400HonigmanERPFileWriter,
		ExportInventProductAS400HonigmanERPFileWriter1,
		ExportInventProductMPLFileWriter2,
		ExportInventProductMPLFileWriter1,
		ExportIturPdaMISFileWriter,
		ExportInventProductTafnitMatrixERPFileWriter1,
		ExportInventProductTafnitMatrixERPFileWriter,
		ExportInventProductPriorityCastroERPFileWriter,
		ExportInventProductPriorityCastroERPFileWriter1,
		ExportInventProductOtechERPFileWriter,
		ExportInventProductOtechERPFileWriter_M,
		ExportInventProductOtechERPFileWriter_T,
		ExportInventProductOtechERPFileWriter_W,
		ExportInventProductOtechERPFileWriter1,
		ExportInventProductOtechERPFileWriter2,
		ExportInventProductNikeIntERPFileWriter,
		ExportInventProductNikeIntERPFileWriter1,
		ExportInventProductWarehouseXslxFileWriter1,
		ExportInventProductWarehouseXslxFileWriter,
		ExportInventProductWarehouseXslxFileFormulaWriter,
		ExportInventProductSapb1XslxERPFileWriter,
		ExportInventProductSapb1XslxERPFileWriter1,
		ExportInventProductSapb1ZometsfarimERPFileWriter,
		ExportInventProductSapb1ZometsfarimERPFileWriter1,
		ExportInventProductGazitVerifoneSteimaztzkyERPFileWriter,
		ExportProductGazitVerifoneSteimaztzkyERPFileWriter,
		ExportInventProductGazitVerifoneSteimaztzkyERPFileWriter1,
		ExportERPCurrentInventorExtendedWriter,
		ExportCurrentInventoryClaitXslxWriter1,
		ExportCurrentInventoryMerkavaXslxWriter1,
		ExportCurrentInventoryMerkavaXslxWriter2_1,
		ExportCurrentInventoryMerkavaXslxWriter2_2,
		ExportCurrentInventoryMerkavaGovXslxWriter2_1,
		ExportCurrentInventoryMerkavaGovXslxWriter2_2,
		ExportInventProductAS400MegaERPFileWriter,
		ExportInventProductAS400MegaERPFileWriter1,
		ExportCurrentInventoryNativXslxWriter1,
		ExportInventProductYellowPazERPFileWriter,
		ExportInventProductPriorityAldoERPFileWriter,
		ExportInventProductAS400HonigmanERPFileWriter2,
		ExportInventProductPrioritySweetGirlXlsxErpFileWriter1,
		ExportInventProductPrioritySweetGirlXlsxErpFileWriter,
		ExportCurrentInventoryNativPlusXslxWriter1,
		ExportCurrentInventoryNativPlusMateAsherXslxWriter1,
		ExportCurrentInventoryMerkavaXslxWriter3,
		ExportCurrentInventoryMerkavaXslxWriter4,
		ExportCurrentInventoryMerkavaXslxWriter5,
		ExportInventProductGeneralXslxFileWriter,
		ExportInventProductAS400HamashbirERPFileWriter1,
		ExportInventProductAS400HamashbirERPFileWriter,
		ExportCurrentInventoryNativPlusXslxWriter2,
		ExportInventProductAS400HoERPFileWriter,
		ExportInventProductAS400HoERPFileWriter1,
		ExportInventProductAS400HoERPFileWriter2,
		ExportInventProductXtechMeuhedetXlsxERPFileWriter1,
		ExportInventProductXtechMeuhedetXlsxERPFileWriter,
		ExportInventProductXtechMeuhedetXlsxERPFileWriter2,
		ExportInventProductH_M_NewERPFileWriter,
		ExportCurrentInventoryNativPlusXslxWriter1_SN,
		ExportCurrentInventoryNativPlusXslxWriter1_Q,
		ExportCurrentInventoryNativPlusYesXslxWriter1,
		ExportCurrentInventoryNativPlusYesXslxWriter1_Q,
		ExportCurrentInventoryNativPlusYesXslxWriter1_SN,
		ExportCurrentInventoryNativPlusYesXslxWriter2,
		ExportCurrentInventoryNativPlusLadpcXslxWriter2,
		ExportCurrentInventoryNativPlusLadpcCsvWriter1,
		ExportInventProductGazitLeeCooperERPFileWriter,
		ExportInventProductNimrodAvivERPFileWriter3,
		ExportCurrentInventoryNativPlusMisradApnimXslxWriter,
		ExportCurrentInventoryStockSonigoXslxWriter1
	}

	public class ImportProviderCaption
	{
		public const string ImportLocationADOProvider = "ImportLocation";
		public const string ImportIturADOProvider = "ImportItur";
		public const string ImportIturERPADOProvider = "ImportIturERP";
		public const string ImportCatalogUnizagADOProvider = "ImportCatalogForUNIZAG";
		public const string ImportInventProductSimpleADOProvider = "ImportInventProduct";
		//public const string ImportInventProductADOProvider1 = "ImportInventProductOld";
		public const string ImportCatalogForComaxASPADOProvider = "ImportCatalogForComaxASP";
		public const string ImportCatalogGazitVerifoneADOProvider = "ImportCatalogForGazitVerifoneASP";
		public const string ImportHamarotGazitVerifoneADOProvider = "ImportHamarotForGazitVerifoneASP";
		public const string ImportCatalogFromDBADOProvider = "ImportCatalogFromDBADOProvider";
		public const string ImportCatalogFromDBBulkProvider = "ImportCatalogFromDBBulkProvider";
		
//    UNIZAG Convert
//>>Catalog_Sample2 : Name: Gazit_Verifone Convert
//>>Catalog_Sample4 : Name: Comax_ASP Convert

	}

	public class ImportProviderFolder
	{
		public const string ImportLocationADOProvider = @"Location";
		public const string ImportIturADOProvider = @"Itur";
		public const string ImportIturERPADOProvider = @"Itur";
		public const string ImportCatalogUnizagADOProvider = @"Catalog";
		public const string ImportInventProductSimpleADOProvider = @"PDA";
//		public const string ImportInventProductADOProvider1 = "ImportInventProductOld";
		public const string ImportCatalogForComaxASPADOProvider = @"Catalog";
		public const string ImportCatalogGazitVerifoneADOProvider = @"Catalog";
		public const string ImportHamarotGazitVerifoneADOProvider1 = @"Catalog";
		public const string ImportHamarotGazitVerifoneADOProvider2 = @"Catalog";
	}

	public enum ImportProviderParmEnum
	{
		MakatMaskRecord = 0,
		MakatMaskTemplate = 1,
		BarcodeMaskRecord = 2,
		BarcodeMaskTemplate = 3,
		WithoutProductName = 4,
		MakatWithoutMask = 5,
		BarcodeWithoutMask = 6,
		Hash = 7,
		FileType = 8,
		QType = 9,
		UseAlphaKey = 10,
		ClientId = 11,
		NewItem = 12,
		CustomerCode = 13,
		CustomerName = 14,
		ActionUpdateProgress = 15,
		CancellationToken = 16,
		CatalogItemCodeStart = 17,
		CatalogItemCodeEnd = 18,
		CatalogItemNameStart = 19,
		CatalogItemNameEnd = 20,
		CatalogPriceBuyStart = 21,
		CatalogPriceBuyEnd = 22,
		HamarotBarcodeStart = 23,
		HamarotBarcodeEnd = 24,
		HamarotItemCodeStart = 25,
		HamarotItemCodeEnd = 26,
		FileName1 = 27,
		FileName2 = 28,
		FileName3 = 29,
		FileName4 = 30,
		FileName5 = 31,
		StoreNumber = 32,
		StoreName = 33,
		CatalogMinLengthIncomingRow = 34,
		Encoding = 35,
		InvertWords = 36,
		ERPNum = 37,
		MaxLen = 38,
		InvertLetters = 39,
		FromCatalog = 40,
		WithoutCatalog = 41,
		CatalogPriceSaleStart = 42,
		CatalogPriceSaleEnd = 43,
		SectionCodeStart = 44,
		SectionCodeEnd = 45,
		SectionNameStart = 46,
		SectionNameEnd = 47,
		UnitTypeCodeStart = 48,
		UnitTypeCodeEnd = 49,
		SupplierCodeStart,
		SupplierCodeEnd,
		FamilyCodeStart,
		FamilyCodeEnd,
		FamilyNameStart,
		FamilyNameEnd,
		QuantityERPStart,
		QuantityERPEnd,
		DBPath,
		DB3Path,
		NewDocumentCode,
		NewSessionCode,
		LocationCode,
		IturCode,
		WithQuantityERP,
		WithFamily,
		WithBarcode,
		IsCreateDb,
		InventorDate,
		InventorDate1,
		QuantityInPackStart,
		QuantityInPackEnd,
		QuantityTypeStart,
		QuantityTypeEnd,
		QuantityInPackEdit,
		IPValueStr1,
		IPValueStr2,
		IPValueStr3,
		IPValueStr4,
		IPValueStr5,
		IPValueStr6,
		IPValueStr7,
		IPValueStr8,
		IPValueStr9,
		IPValueStr10,
		IPValueStr11,
		IPValueStr12,
		IPValueStr13,
		IPValueStr14,
		IPValueStr15,
		IPValueStr16,
		IPValueStr17,
		IPValueStr18,
		IPValueStr19,
		IPValueStr20,
		IPValueFloat1,
		IPValueFloat2,
		IPValueFloat3,
		IPValueFloat4,
		IPValueFloat5,
		IPValueInt1,
		IPValueInt2,
		IPValueInt3,
		IPValueInt4,
		IPValueInt5,
		IPValueBit1,
		IPValueBit2,
		IPValueBit3,
		IPValueBit4,
		IPValueBit5,
		IturNameType,
		IturNamePrefix,
		IturNameSuffix,
		InvertPrefix,
		BranchName,
		BranchCode,
		Delimiter,
		PriceCode,
		ExcludeNotExistingInCatalog,
		CreateDateTime,
		CodeReport,
		IncludeProductMakatWithoutInventProduct,
		Password,
		InventorCode,
		Path1,
		SourcePath,
		FileXlsx,
		SheetNumberXlsx,
		SheetNameXlsx,
		FileDB3,
		MISiDnextDataPath,
		MISCommunicatorPath,
		HTcalculateLookUp,
		LookUpEXE,
		OnlyWithMask,
		AddNewLocation,
		MaxQuantity,
		LastSync,
		InvertWordsConfig,
		InvertLettersConfig,
		CutAfterInvert,
		AllowZeroQuantity,
		SearchDef,
		NewItemBool,
		FileXlsxTemplate,
		XlsxTemplatePath,
		FileXlsm,
		SupplierNameStart,
		SupplierNameEnd,
		IncludeCurrentInventor,
		IncludeProfile,
		IsAddBinarySearch,
		ConfirmNewLocation,
		ConfirmNewItem,
		AutoSendData,
		DestinationPath,
		AllowQuantityFraction,
		AddExtraInputValue,
		AddExtraInputValueHeaderName,
		FromBuildAnalyze,
		PropertyName,
		Count,
		AddExtraInputValueSelectFromBatchListForm,
		AllowNewValueFromBatchListForm,
		SearchIfExistInBatchList,
		AllowMinusQuantity	,
		FractionCalculate		 ,
		PartialQuantity,
		Host1,
		Host2	,
		Approve	,
		Timeout,
		Retry,
		SameBarcodeInLocation,
		DefaultHost	,
		UpdatePriceBuy,
		UpdatePriceSell,
		UpdateSN
	}

	public class ImportProviderParmName
	{
		public const string Hash = "Hash";
		public const string FileType = "FileType";
		public const string QType = "QType";
		public const string UseAlphaKey = "UseAlphaKey";
		public const string ClientId = "ClientId";
		public const string NewItem = "NewItem";
		public const string NewItemBool = "NewItemBool";
		public const string Password = "Password";
		public const string IturNameType = "IturNameType";
		public const string IturNamePrefix = "IturNamePrefix";
		public const string CustomerName = "CustomerName";
		public const string CustomerCode = "CustomerCode";
		public const string BranchName = "BranchName";
		public const string BranchCode = "BranchCode";
		public const string StoreNumber = "StoreNumber";
		public const string StoreName = "StoreName";
		public const string QuantityType = "QuantityType";
		public const string AddNewItem = "AddNewItem";
		public const string Count4uCode = "Count4uCode";
		public const string LookUpEXE = "LookUpEXE";
		public const string HTcalculateLookUp = "HTcalculateLookUp";
		public const string AddNewLocation = "AddNewLocation";
		public const string MaxQuantity = "MaxQuantity";
		public const string AllowZeroQuantity = "AllowZeroQuantity";
		public const string LastSync = "LastSync";
		public const string IsInvertWordsConfig = "IsInvertWordsConfig";
		public const string IsInvertLettersConfig = "IsInvertLettersConfig";
		public const string IsCutAfterInvert = "IsCutAfterInvert";
		public const string SearchDef = "SearchDef";
		public const string ConfirmNewLocation = "ConfirmNewLocation";
		public const string ConfirmNewItem = "ConfirmNewItem";
		public const string AutoSendData = "AutoSendData";

	 	public const string AllowQuantityFraction = "AllowQuantityFraction";
		public const string AddExtraInputValue = "AddExtraInputValue";
		public const string AddExtraInputValueHeaderName = "AddExtraInputValueHeaderName";

		public const string AddExtraInputValueSelectFromBatchListForm = "AddExtraInputValueSelectFromBatchListForm";
		public const string AllowNewValueFromBatchListForm = "AllowNewValueFromBatchListForm";
		public const string SearchIfExistInBatchList = "SearchIfExistInBatchList";
		public const string AllowMinusQuantity = "AllowMinusQuantity";
		public const string FractionCalculate = "FractionCalculate";
		public const string PartialQuantity = "PartialQuantity";
		public const string Host1 = "Host1";
		public const string Host2 = "Host2";
		public const string Timeout = "Timeout";
		public const string Retry = "Retry";
		public const string SameBarcodeInLocation = "SameBarcodeInLocation";
		public const string DefaultHost = "DefaultHost";
		
		 
	}


	
}
